mysite/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from rest_framework import routers
from api import views
from django.conf import settings
from polls.views import pollsAngularApp

router = routers.DefaultRouter()
router.register(r'polls', views.PollsViewSet, base_name='polls')
router.register(r'choices', views.ChoiceViewSet, base_name='choices')
router.register(r'users', views.UserViewSet, base_name='users')
admin.autodiscover()

urlpatterns = patterns('',
                       (r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT}),
                       (r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
                       url(r'^polls/', include('polls.urls', namespace="polls")),
                       url(r'^polls_app/', pollsAngularApp.as_view()),
                       url(r'^admin/', include(admin.site.urls)),
                       url(r'^api/', include(router.urls)),
                       )

polls/urls.py
from django.conf.urls import patterns, url

from . import views


urlpatterns = patterns('',
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^all/$', views.AllView.as_view(), name='all'),
    url(r'^users/$', views.UserIndexView.as_view(), name='users'),
    url(r'^users/(?P<pk>\d+)/$', views.UserDetailView.as_view(), name='user_detail'),
    url(r'^new/$', views.new, name='new'),
    url(r'^(?P<pk>\d+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<pk>\d+)/results/$', views.ResultsView.as_view(), name='results'),
    url(r'^(?P<poll_id>\d+)/vote/$', views.vote, name='vote'),
    url(r'^(?P<poll_id>\d+)/add/$', views.add, name='add'),
)

polls/models.py
import datetime

from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User


class Poll(models.Model):
    question = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published', default=datetime.datetime.now)

    def __unicode__(self):  # Python 3: def __str__(self):
        return self.question

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date < now

    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'


class Choice(models.Model):
    poll = models.ForeignKey(Poll)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    user = models.ForeignKey(User, null=True, blank=True, default=None)

    def __unicode__(self):  # Python 3: def __str__(self):
        return self.choice_text

class Vote(models.Model):
    poll = models.ForeignKey(Poll)
    choice = models.ForeignKey(Choice)
    user = models.ForeignKey(User)
    timestamp = models.DateTimeField(default=datetime.datetime.now)

    def __unicode__(self): 
        return unicode(self.choice)

polls/forms.py
from django.forms import ModelForm
from django.forms.models import inlineformset_factory

from polls.models import Poll, Choice

ChoiceFormSet = inlineformset_factory(Poll, Choice,
                                    fields=['choice_text'],
                                    can_delete=False,
                                    extra=5)

class PollForm(ModelForm):
    class Meta:
        model = Poll
        fields = ['question',]

class ChoiceForm(ModelForm):
    class Meta:
        model = Choice
        fields = ['choice_text',]

polls/views.py
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.utils import timezone
from django.views import generic

from .models import Choice, Poll, Vote
from .forms import PollForm, ChoiceFormSet, ChoiceForm
from django.contrib.auth.models import User


class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_poll_list'

    def get_queryset(self):
        """
        Return the last five published polls (not including those set to be
        published in the future).
        """
        return Poll.objects.filter(
            pub_date__lte=timezone.now()
        ).order_by('-pub_date')[:5]

class AllView(generic.ListView):
    template_name = 'polls/all.html'

    def get_queryset(self):
        """
        Return all existing (not including those set to be
        published in the future).
        """
        return Poll.objects.filter(
            pub_date__lte=timezone.now()
        ).order_by('-pub_date')

class UserIndexView(generic.ListView):
    template_name = 'polls/user_index.html'
    context_object_name = 'user_list'

    def get_queryset(self):
        """
        Return all users
        """
        return User.objects.all()

class UserDetailView(generic.DetailView):
    model = User
    template_name = 'polls/user_detail.html'
    context_object_name = 'user_object'

class DetailView(generic.DetailView):
    model = Poll
    template_name = 'polls/detail.html'

    def get_queryset(self):
        """
        Excludes any polls that aren't published yet.
        """
        return Poll.objects.filter(pub_date__lte=timezone.now())

    def get_context_data(self, **kwargs):
        context = super(DetailView, self).get_context_data(**kwargs)
        context['existing_vote'] = Vote.objects.filter(user=self.request.user.id, poll=self.get_object()).first()
        context['choice_form'] = ChoiceForm()
        context['authenticated_user'] = self.request.user.is_authenticated()
        return context


class ResultsView(generic.DetailView):
    model = Poll
    template_name = 'polls/results.html'


def vote(request, poll_id):
    p = get_object_or_404(Poll, pk=poll_id)
    try:
        selected_choice = p.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the poll voting form.
        return render(request, 'polls/detail.html', {
            'poll': p,
            'error_message': "You didn't select a choice.",
        })
    else:
        if request.user.is_authenticated():
            user = request.user
            if Vote.objects.filter(user=user, poll=p).exists():
                return render(request, 'polls/detail.html', {
                                'poll': p,
                                'error_message': "You have already voted in this poll",
                            })
            else: 
                selected_choice.votes += 1
                selected_choice.save()
                vote = Vote(user=user, poll=p, choice=selected_choice)
                vote.save()
                # Always return an HttpResponseRedirect after successfully dealing
                # with POST data. This prevents data from being posted twice if a
                # user hits the Back button.
                return HttpResponseRedirect(reverse('polls:results', args=(p.id,)))
        else:
            return render(request, 'polls/detail.html', {
                'poll': p,
                'error_message': "You must be logged in to vote",
            })

def new(request):
    if request.POST: 
        form = PollForm(request.POST)
        if form.is_valid():
            poll = form.save(commit=False)
            choice_formset = ChoiceFormSet(request.POST, instance=poll)
            if choice_formset.is_valid():
                poll.save()
                choice_formset.save()
                return HttpResponseRedirect(reverse('polls:detail', args=(poll.id,)))
    else:
        form = PollForm()
        choice_formset = ChoiceFormSet(instance=Poll())
    return render(request, 'polls/new.html', {
        'form': form,
        'choice_formset': choice_formset,
    })

def add(request, poll_id):
    poll = get_object_or_404(Poll, pk=poll_id)
    if request.user.is_authenticated():
        user = request.user
        if request.POST: 
            form = ChoiceForm(request.POST)
            if form.is_valid():
                new_choice = form.save(commit=False)
                new_choice.poll = poll
                new_choice.user = user
                new_choice.save()
                return HttpResponseRedirect(reverse('polls:detail', args=(poll.id,)))
    else: 
        return render(request, 'polls/detail.html', {
                'poll': poll,
                'error_message': "You must be logged in to submit a new choice",
            })

class pollsAngularApp(generic.TemplateView):
    template_name = 'base.html'

polls/templates/polls/all.html
{% if poll_list %}
    <ul>
    {% for poll in poll_list %}
    <li><a href="{% url 'polls:detail' poll.id %}">{{ poll.question }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

polls/templates/polls/answered.html
{% if user_list %} 
  <ul>
    {% for user in user_list %}
      <li>{{user.username}}</li>
        <ul>
          {% for vote in user.vote_set.all %}
              <li><a href="{% url 'polls:detail' vote.poll.id %}">{{vote.poll}}</a> -- {{vote.choice}}</li>
          {% endfor %}
        </ul>
    {% endfor %}
  </ul>
{% endif %}

polls/templates/polls/detail.html
<h1>{{ poll.question }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' poll.id %}" method="post">
{% csrf_token %}
{% for choice in poll.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" 
            {% if existing_vote %} disabled {% endif %}
            {% if existing_vote.choice == choice %} checked="checked"{% endif %}
    />
    <label for="choice{{ forloop.counter }}"/>{{ choice.choice_text }}  
        {% if choice.user %}
            <em> -- added by {{choice.user.username}}</em>
        {% endif %}
    </label><br />
{% endfor %}
{% if not existing_vote %}
  <input type="submit" value="Vote" />
{% endif %}
</form>

{% if authenticated_user %}
<form action="{% url 'polls:add' poll.id %}" method="post">
    {% csrf_token %}
    {{choice_form}}
    <input type="submit" name="submit" value="Submit" class="button">
</form>
{% endif %}

polls/templates/polls/index.html
{% if latest_poll_list %}
    <ul>
    {% for poll in latest_poll_list %}
		<li><a href="{% url 'polls:detail' poll.id %}">{{ poll.question }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

polls/templates/polls/new.html
<h1>Create a new poll</h1>

<form action="/polls/new/" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    {{ choice_formset.as_p }}
    <input type="submit" name="submit" value="Submit" class="button">
</form>

polls/templates/polls/results.html
<h1>{{ poll.question }}</h1>

<ul>
{% for choice in poll.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' poll.id %}">Vote again?</a>

polls/templates/polls/user_detail.html
<h1>{{user_object.username}}</h1>

{% if user_object.vote_set.exists %}
  <ul>
    {% for vote in user_object.vote_set.all %}
        <li><a href="{% url 'polls:detail' vote.poll.id %}">{{vote.poll}}</a> -- {{vote.choice}}</li>
    {% endfor %}
  </ul>
{% else %}
  <em>{{user_object.username}} hasn't voted on any polls</em>
{% endif %}

polls/templates/polls/user_index.html
{% if user_list %} 
  <ul>
    {% for user in user_list %}
      <li><a href="{% url 'polls:user_detail' user.id %}">{{user.username}}</a></li>
    {% endfor %}
  </ul> 
{% endif %}